Radlet/radlet-dock

- CMakeLists.txt
- Docker/deploy.Dockerfile
- Docker/dev.Dockerfile
- Docker/env.Dockerfile
- README.md
- libs/sqlite3pp/inc/sqlite3pp.h
- libs/sqlite3pp/inc/sqlite3pp.ipp
- main.cpp
SQLite 3 wrapper added
https://github.com/iwongu/sqlite3pp
- Headers added (header only lib)
- Cmake updated
- Dockerfile updated
> SQLite3 wrapper added

- Docker/env.Dockerfile
- Docker/install/protobuf.sh
#12 
Protobuf installation to image.
- Added script in Docker/install/protobuf.sh for protobuf insatallation from source.
- Modified Docker/env.Dockerfile to run protobuf.sh
N
> Added protobuf installation to image

- CMakeLists.txt
- protos/thing_buffer.proto
- protos/user.proto
- src/main.cpp
#8 
Proto for user.
- Added demo for user proto.
- Added user proto.
N
> User proto

- .github/ISSUE_TEMPLATE/refactor.md
Added a new refactor template for the repository
> Added a refactor issue template

- src/CMakeLists.txt
- src/io/adaptor/udp/inc/udp_interface.h
- src/io/adaptor/udp/src/udp_interface.cpp
- src/main.cpp
- src/utils/ip_map/inc/ip_map.h
- src/utils/port_map/inc/port_map.h
#22 
UDP server has been setup that listens to multicast messages sent from IOT servers.
- added port and ip maps
- added udp_interface
- added io_service and passed a shared pointer to udp_service
N
> UDP server finalized

- src/main.cpp
#27 
- Start server in separate contexts.
- Started udp server.
- Started http server.
<Y / N>
> Create server on separate threads.

- Docker/deploy.Dockerfile
- Docker/dev.Dockerfile
- package.sh
- src/io/adaptor/udp/inc/udp_interface.h
- src/io/adaptor/udp/src/udp_interface.cpp
#25
Fixed the docker issue of udp traffic, refactored udp code according to proxygen docs, added -mt flag for testing manually
- Docker files updated
- package.sh modified
- udp_interface.h modified
N
Note: Instead of using the bridge network, we are using the host network now, thus the docker issue has been resolved
> Udp refactor and package.sh update for manual testing

- .gitmodules
#10 
- Add cpr repor
- Added cpr repo
N
> Added CPR repository as submodule

- .gitmodules
- CMakeLists.txt
- Docker/scripts/base.sh
- src/CMakeLists.txt
- src/main.cpp
- src/utils/influxdb_utils/inc/influxdb_utils.h
- src/utils/influxdb_utils/src/influxdb_utils.cpp
#10 
- Added support for Influx DB integration.
- Added cpr library for http request processing.
- Influxdb utils
- cpr submodule addition.
N
> Added Influx API support.

- Docker/dev.Dockerfile
- Docker/scripts/base.sh
- Docker/scripts/protobuf.sh
- package.sh
#39 
Docker files and shell scripts cleaned up
- DockerFiles
- Scripts
N
> Docker files refactored

- src/CMakeLists.txt
- src/core/db/inc/db_interface.h
- src/core/db/src/db_interface.cpp
- src/main.cpp
#44 
Basic interface for device db has been set up. DB file is being created when the server starts.
- Made changes to cmake file for linking sqilte3
- created a new class for saving device data
N
> device db basic interface working

- src/core/discovery/src/discovery_handler.cpp
- src/io/adaptor/tcp/src/http_interface.cpp
#32
IOT device now sends data as JSON string. The UDP interface of the Hub has been modified to accommodate for that change.
(Code has been tested from my end)
- ./core/discovery
N
> UDP interface JSON parser added

- Docker/deploy.Dockerfile
- Docker/deploy.docker-compose.yml
- Docker/dev.docker-compose.yml
- package.sh
#50 
Docker compose files have been added for making influx db container work in sync with hub container. Package.sh has been updated accordingly.
- package.sh
- ./Docker/deploy.docker-compose.yml
- ./Docker/dev.docker-compose.yml
N
> Docker compose files added, package.sh updated

- src/core/db/inc/db_interface.h
- src/core/discovery/inc/discovery_handler.h
- src/core/discovery/src/discovery_handler.cpp
- src/io/adaptor/tcp/inc/http_interface.h
- src/io/adaptor/udp/inc/udp_interface.h
- src/io/adaptor/udp/src/udp_interface.cpp
#52
Code comments added to the header files written so far
- UDP
- TCP
- Discovery
- DB
N
> Added comments and refactored code for UDP, TCP and discovery

- src/CMakeLists.txt
- src/main.cpp
- src/utils/log/inc/log.h
- src/utils/log/src/log.cpp
> Logger added

- src/CMakeLists.txt
- src/main.cpp
- src/utils/log/inc/log.h
- src/utils/log/src/log.cpp
- src/utils/short_time_data/inc/short_time_data.h
#48 
- Logger and time based data structure.
- Global logger added.
- Time based data structure with default timeout 30seconds.
N
> Time based ds

- src/main.cpp
- src/utils/log/inc/log.h
- src/utils/log/src/log.cpp
Hotfix
Makes some minor cosmetic changes in the logger file
- Log.h
- Log.cpp
- main.cpp
N
> Logger file refactored

- .vscode/settings.json
- protos/device.proto
- src/core/db/inc/persistent_data_interface.h
- src/core/db/inc/sensor_data_interface.h
- src/core/db/inc/temporary_data_interface.h
- src/core/db/src/persistent_data_interface.cpp
- src/core/db/src/sensor_data_interface.cpp
- src/core/db/src/temporary_data_interface.cpp
- src/core/discovery/src/discovery_handler.cpp
- src/io/adaptor/udp/inc/udp_interface.h
- src/main.cpp
#57 
The ShortTimeData structure needs a wrapper so that it can be used globally as a static class.
- core/db
- io/udp
N
> Temporary db wrapper completed

- src/CMakeLists.txt
- src/core/db/inc/temporary_data_interface.h
- src/core/db/src/temporary_data_interface.cpp
- src/io/adaptor/tcp/src/http_interface.cpp
- src/main.cpp
#60
Fetch available device list API working
- io/tcp/http
N
> fetch available device list API working

- CMakeLists.txt
- Docker/deploy.Dockerfile
- Docker/deploy.docker-compose.yml
- Docker/dev.Dockerfile
- Docker/dev.docker-compose.yml
- package.sh
#62 
The following has been done in this PR
As planned, the following list of changes have been made
N
> Docker file, Docker images and cmake var names changed

- src/main.cpp
- src/utils/short_time_data/inc/short_time_data.h
#62 
- Comment and query modification in short_time_data templates.
- Comments to ShortTimeData member functions.
- Method for batch addition of data items.
- Method for batch retrieval of data items.
N
> Minor modifications to short_time_data

- src/core/db/inc/temporary_data_interface.h
- src/core/db/src/temporary_data_interface.cpp
- src/core/discovery/src/discovery_handler.cpp
- src/io/adaptor/tcp/src/http_interface.cpp
- src/utils/short_time_data/inc/short_time_data.h
#67 
The STDS interface has been integrated with the getallDevices API
- io/tcp
- short time data structure
N
> Get all devices API integrated with STDS

- protos/device.proto
- src/core/discovery/inc/discovery_handler.h
- src/core/discovery/src/discovery_handler.cpp
- src/io/adaptor/tcp/src/http_interface.cpp
- src/io/adaptor/udp/src/udp_interface.cpp
#71 
WOT (partial) have been added on the IOT device and thus modifications have been made on the dock as well to accommodate for these changes.
- discovery
- udp
N
> WOT standard compatibility added

- Docker/deploy.Dockerfile
- Docker/deploy.docker-compose.yml
- Docker/dev.Dockerfile
- Docker/dev.docker-compose.yml
- README.md
- package.sh
#73 
README.md and Docker files updated
- Readme updated
- docker files modified
N
> README.md and Docker files updated

- LICENSE.md
- src/core/db/inc/temporary_data_interface.h
- src/core/discovery/inc/discovery_handler.h
- src/core/discovery/src/discovery_handler.cpp
- src/io/adaptor/tcp/inc/http_interface.h
- src/io/adaptor/tcp/src/http_interface.cpp
- src/main.cpp
- src/utils/short_time_data/inc/short_time_data.h
#68
Attach API completed, tested with composer and plankton
- Discovery
- io/tcp
N
> Attach API completed, tested with composer and plankton

- .github/workflows/buildtest.yml
- .github/workflows/dockercicd.yml
- package.sh
#80 
Need to update dockerhub image on every successful merge to master
- workflow files
N
> docker hub image update yaml added

- .github/workflows/buildtest.yml
- .github/workflows/dockercicd.yml
- src/core/db/inc/persistent_data_interface.h
- src/core/db/src/persistent_data_interface.cpp
- src/core/discovery/inc/discovery_handler.h
- src/core/discovery/src/discovery_handler.cpp
- src/io/adaptor/tcp/inc/http_interface.h
- src/io/adaptor/tcp/src/http_interface.cpp
#81 
Attach and Detach API integrated with Plankton and Composer
- discovery
- persistantData
- tcp interface
N
> Attachment and Detachment API integrated with persistant DB

- src/core/db/inc/persistent_data_interface.h
- src/core/db/src/persistent_data_interface.cpp
- src/core/discovery/inc/discovery_handler.h
- src/core/discovery/src/discovery_handler.cpp
- src/io/adaptor/tcp/inc/http_interface.h
- src/io/adaptor/tcp/src/http_interface.cpp
- src/io/adaptor/udp/src/udp_interface.cpp
#86 
Function names refactored
- Renamed functions
- Added docs
- Renamed routes
N
> Function names refactored (Discovery, HTTP, DB)

- CMakeLists.txt
- Docker/arm/env.Dockerfile
- Docker/scripts/protobuf.sh
- Docker/scripts/rxcpp.sh
- Docker/x64/env.Dockerfile
- src/CMakeLists.txt
#85 
Included the rxcpp library in the env docker file, updated on docker hub, tested with build images
- Cmake
N
> RXcpp library added to env docker, tested with build

- src/io/adaptor/udp/src/udp_interface.cpp
- src/main.cpp
- src/utils/async_manager/inc/async.h
#89 
Execute method added in Async Manager
- Added execute method.
- Started TCP and UP servers on with Async manager.
N
> Add functionality to execute any method on singleton instance's thread pool.
